### PR TITLE
fix: include query params in response `url` field

### LINKED ISSUE #39: Render removes query parameters
I'm currently trying to build pagination into my application but  it seems like the `Response` returned by the render function removes query params set in the browser. For example if i call `/table?page=0` the response just leaves me with `/table`. Is there any way I can prevent this?

### PR DESCRIPTION
**Pull request by Dsaquel**
fix #39
The response route url from axum_inertia remove query params, fixed it.

### CODE REVIEW

**Comment by mjhoy** [comment]
Thanks for the PR! Sorry I didn't respond to your issue, my last month has been busy. I should have time to review this week.

**Comment by Dsaquel** [comment]
No problem at all, we all have higher priority 👍.

File: src/request.rs [hunk 1]
```diff
@@ -38,7 +38,13 @@ where
         let original_uri = OriginalUri::from_request_parts(parts, state)
             .await
             .unwrap_or_else(|e| match e {});
-        let url = original_uri.0.path().to_string();
+        let query_string = parts
+            .uri
+            .to_string()
```
Comment (mjhoy) [inline src/request.rs:43]: i think we can use the [`query` method](https://docs.rs/http/latest/http/uri/struct.Uri.html#method.query) here on the `uri` to simplify this

File: src/request.rs [hunk 2]
```diff
@@ -38,7 +38,13 @@ where
...
+            .split_once("?")
+            .map(|(_, second_half)| format!("?{second_half}"))
+            .unwrap_or_default();
+        let url = format!("{}{}", original_uri.0.path(), query_string);
```
Comment (mjhoy) [inline src/request.rs:47]: i actually think it might be helpful here to either a) break apart the path (`String`) and query (`Option<String>`) as separate fields on `Request`, _or_ just carry forward the whole `parts.uri` here. we would then need to update the `Inertia::render` method to build the final `url` but I think I like that a little better. thoughts on that?

**Review by mjhoy — CHANGES_REQUESTED** [review]
thanks for the pr! one small suggestion and another thought about updating the `Request` type

File: src/request.rs (hunk 2 above)
Comment (Dsaquel) [reply src/request.rs]: I found that we can only do:
```diff
- let url = original_uri.0.path().to_string();
+ let url = original_uri.to_string();
```
to get query inside. Do you still want to have path and query separate in `Request` ?

Comment (mjhoy) [reply src/request.rs]: I actually like using `to_string` on `Uri` like this. I may refactor a bit later to pass the `Uri` in the request rather than the string, but this is good for now.

**Review by mjhoy — APPROVED** [review]

File: src/request.rs (hunk 2 above)
Comment (Dsaquel) [reply src/request.rs]: Alright, thanks !

**Comment by mjhoy** [comment]
released as v0.7.0
